### ISSUE TITLE
"lapd/nopixel inspired car pack"

### ISSUE THREAD

**Issue by trclassic92** [Bunny5578/LapdCarPack#2]
Oh You mean something that I have already done 🤣 

https://trclassic.tebex.io/package/5207048

https://trclassic.tebex.io/package/5055336

**Comment by trclassic92** [comment]
![msedge_nEpma2AJPF](https://user-images.githubusercontent.com/82931913/184092530-dd75dd4f-a29f-4a57-ae0b-9bc4e826e1d2.png)

Also, you do understand what you are doing you are not allowed to do. They clearly say you are not allowed to reupload these vehicles but yet here you are doing so.

**Comment by Bunny5578** [comment]
Thank you for bringing this to my attention for the second comment that was a my bad i didn't read the descriptions of theses models and will be looking to change them asap 

Now for the first comment that's cool you have already done it good for you I'm still going to be finishing this lmao plus mines free also doesn't make it better I am making this for the people that don't have $60 to spend but would like some decent nopixel liverys that aren't leaked🙂

**Comment by trclassic92** [comment]
The only reason the price is expensive for them is because of the time and effort it takes to make those kinds of liveries. 

I don't disagree with your last statement

 "but thought I would give everyone the chance to use the nopixel inspired liverys"

Which is the reason why I created all of them but at a price because like I said of the time and effort it takes to make a correct version of the liveries.

**Comment by Bunny5578** [comment]
Yeah of course and it makes sense yours took lots and lots of time to make it as accurate and high quality as possible not saying that you charging that is stupid I agree with the price 🤙 just was saying why I made this I also added in your link and some credits if that's okay with you for people that are actually looking for the exact replica of no pixels cop cars 🙂

**Comment by trclassic92** [comment]
Yeah, I'm cool with you adding my link to your read me 😄. I just thought you were looking for some that were already made.

**Comment by Bunny5578** [comment]
All good I appreciate ya bring that to my attention btw I just looked at the model thought it looked good and downloaded XD
